// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSD.RazorData.Models.SysMapper.Views
{
    public partial class VCategory
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public int? LifeCycleId { get; set; }
        public string LifeCycleName { get; set; }
    }
}