// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSD.RazorData.Models.SysMapper.Views
{
    public partial class VLabelMap
    {
        public int LabelMapId { get; set; }
        public int? LifeCycleId { get; set; }
        public string LifeCycleName { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int? TagId { get; set; }
        public string TagName { get; set; }
    }
}