// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSD.RazorData.Models.SysMapper.Views
{
    public partial class VLabelType
    {
        public int LabelTypeId { get; set; }
        public string Name { get; set; }
        public int? LifeCycleId { get; set; }
        public string LifeCycleName { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int? OuId { get; set; }
        public string Organization { get; set; }

    }
}