// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSD.RazorData.Models.SysMapper.Views
{
    public partial class VLifeCycle
    {
        public int LifeCycleId { get; set; }
        public string Name { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}