// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OSD.RazorData.Models.SysMapper.Views
{
    public partial class VOu
    {
        public int OuId { get; set; }
        public string Organization { get; set; }

        public int? LifeCycleId { get; set; }
        public string LifeCycleName { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}